Repository kbef/group1apk, pull requests merged in 2020-03, with the labels that each got.

#23 Download database changes
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/group1/EngPlan/Adapters/CourseChoiceAdapter.java
  app/src/main/java/com/group1/EngPlan/Adapters/LoginDialog.java
  app/src/main/java/com/group1/EngPlan/CentralActivity.java
  app/src/main/java/com/group1/EngPlan/ChangeDatabase.java
  app/src/main/java/com/group1/EngPlan/CourseDetails.java
  app/src/main/java/com/group1/EngPlan/DatabaseHandler.java
  app/src/main/java/com/group1/EngPlan/MainActivity.java
  app/src/main/java/com/group1/EngPlan/MakeAPlan/PassFailScreen.java
  app/src/main/res/drawable/rounded_button3.xml
  app/src/main/res/layout/activity_change_db.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/alert_dialog_layout.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#25 Algorithm
  app/src/main/java/com/group1/EngPlan/CentralActivity.java
  app/src/main/java/com/group1/EngPlan/DatabaseHandler.java
  app/src/main/java/com/group1/EngPlan/MakeAPlan/PassFailScreen.java
  app/src/main/java/com/group1/EngPlan/schedule_generator.java
Labels: enhancement, help wanted

#28 Squashed Bugs in Algorithm - March 10 2020
  app/src/main/java/com/group1/EngPlan/CentralActivity.java
  app/src/main/java/com/group1/EngPlan/MakeAPlan/MakeAPlanYearScreen.java
  app/src/main/java/com/group1/EngPlan/MakeAPlan/PassFailScreen.java
  app/src/main/java/com/group1/EngPlan/schedule_generator.java
Labels: bug, enhancement

#32 Upload database from external file
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/group1/EngPlan/Adapters/LoginDialog.java
  app/src/main/java/com/group1/EngPlan/ChangeDatabase.java
  app/src/main/java/com/group1/EngPlan/DatabaseHandler.java
  app/src/main/java/com/group1/EngPlan/MainActivity.java
  app/src/main/java/com/group1/EngPlan/MakeAPlan/PassFailScreen.java
  app/src/main/java/com/group1/EngPlan/QuickView.java
  app/src/main/res/layout/activity_change_db.xml
Labels: enhancement
